### ISSUE TITLE
Slightly more robust readme?

### ISSUE THREAD

**Issue by EnduringBeta** [NewsappAJC/gga#22]
Howdy! I'm interested in knowing more about just what this project was about, and what it did. I hit one too many errors trying to get it to run (maybe I just need an older Grunt), so I thought a question here might be quicker. I want to know if anything here would benefit me to build upon for an idea I have to make alerting users to new legislation and updates easier.

**Comment by NewsappAJC** [comment]
Hi Ross,

That is an ancient version of the code behind the AJC's Legislative
Navigator (https://legislativenavigator.ajc.com/). The app's been
completely rewritten since then, and now resides in a private repository.
Probably not much there worth salvaging.

If you don't know already, the general assembly has a public data api with
information about bills that they update nightly. If you contact Brian
Hurst (Brian.Hurst@legis.ga.gov), he can send you the documentation.

John Perry

Data Journalism Team Technical Director

The Atlanta Journal-Constitution
John.Perry@ajc.com

404-526-5696
